#This Docker-compose is what ties all the containers together. 
#This makes for brining up DMS Service easier
version: "3.3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./dms-lite
    ports:
      - "3000:3000"
    volumes:
      - "${DATABASE_FILE}:/db"

  wifi-writer:
      build:
        dockerfile: Dockerfile
        context: ./Wifi-sql-writer
      volumes:
        - "${DATABASE_FILE}:/db"
          
