#This Docker-compose is what ties all the containers together. 
#This makes for brining up DMS Service easier
version: "3.3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./dms-lite
    ports:
      - "3000:3000"
    volumes:
      - "${DATABASE_FILE}:/db"

  MQTT-Server:
      container_name: mqtt_broker
      hostname: mosquitto
      image: eclipse-mosquitto:2.0.10
      ports: 
        - "1883:1883"
      volumes:
          - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  wifi-writer:
      depends_on:
        - "MQTT-Server"
      build:
        dockerfile: Dockerfile
        context: ./Wifi-sql-writer
      volumes:
        - "${DATABASE_FILE}:/db"
          
